//
//  LoginPresenterTests.swift
//  TesteSantander
//
//  Created by Rodrigo Martins on 23/05/2019.
//  Copyright (c) 2019 Rodrigo Martins. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TesteSantander
import XCTest

class LoginPresenterTests: XCTestCase{
    var sut: LoginPresenter!
    
    override func setUp() {
        super.setUp()
        setupLoginPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }

    func setupLoginPresenter() {
        sut = LoginPresenter()
    }
}
