//
//  LoginModels.swift
//  TesteSantander
//
//  Created by Rodrigo Martins on 29/04/19.
//  Copyright (c) 2019 Rodrigo Martins. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct LoginResponse: Codable {
    var userAccount: AccountData?
    var error: Error?
    
    struct AccountData: Codable {
        var userId: Int = 0
        var name: String?
        var agency: String?
        var bankAccount: String?
        var balance: Double?
    }
    
    struct Error: Codable {
        var message: String?
    }
}
