//
//  LoginRouter.swift
//  TesteSantander
//
//  Created by Rodrigo Martins on 29/04/19.
//  Copyright (c) 2019 Rodrigo Martins. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic{
  func routeTosegueDetailAccountWith(_ segue: UIStoryboardSegue?)
}

protocol LoginDataPassing{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing{
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeTosegueDetailAccountWith(_ segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationViewController = segue.destination as! DetailViewController
            var destinationDataStore = destinationViewController.router!.dataStore!
            
            sendAccountInformation(source: dataStore!, destination: &destinationDataStore)
        }
    }
    
    // MARK: Navigation
    
    func navigateToExtractView(source: LoginViewController, destination: DetailViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func sendAccountInformation(source: LoginDataStore, destination: inout DetailDataStore) {
        print(source.userAccount!)
        destination.userAccount = source.userAccount
    }
}
