//
//  LoginPresenter.swift
//  TesteSantander
//
//  Created by Rodrigo Martins on 29/04/19.
//  Copyright (c) 2019 Rodrigo Martins. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func showAlert(title: String, message: String) -> Void
    func login(loginResponse: LoginResponse) -> Void
}

class LoginPresenter: LoginPresentationLogic {
    
    weak var viewController: LoginDisplayLogic?

    func showAlert(title: String, message: String) {
        let customAlert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        customAlert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
        
        if let viewController = viewController{
            viewController.failure(alertController: customAlert)
        }
    }
    
    func login(loginResponse: LoginResponse) {
        if let viewController = viewController {
            viewController.success(dataUserAccount: loginResponse)
        }
    }
}
