//
//  LoginWorker.swift
//  TesteSantander
//
//  Created by Rodrigo Martins on 29/04/19.
//  Copyright (c) 2019 Rodrigo Martins. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

typealias responseHandler = (_ response: LoginResponse) -> ()

class LoginWorker{
    func validateLogin(parameters: Dictionary<String,String>, responseRequest: @escaping(responseHandler)) {
        guard let url = URL(string: "https://bank-app-test.herokuapp.com/api/login") else {return}
        var requisicao = URLRequest(url: url)
        requisicao.httpMethod = "POST"
        
        
        let json = try! JSONSerialization.data(withJSONObject: parameters, options: [])
        requisicao.httpBody = json
        requisicao.addValue("application/json", forHTTPHeaderField: "Content-Type")
        Alamofire.request(requisicao).responseJSON(completionHandler: { response in
            switch response.result {
            case .success(_):
                do {
                    if let data = response.data {
                        let loginResponse = try JSONDecoder().decode(LoginResponse.self, from: data)
                        responseRequest(loginResponse)
                    }
                } catch (let error) {
                    print(error)
                }
            case .failure(let error):
                print(error)
            }
        })
    }
}
