//
//  DetailWorker.swift
//  TesteSantander
//
//  Created by Rodrigo Martins on 29/04/19.
//  Copyright (c) 2019 Rodrigo Martins. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

typealias detailHandler = (_ response: DetailResponse) -> ()

class DetailWorker{
    let url: String = "https://bank-app-test.herokuapp.com/api/statements/"
    
    func getExtractList(extractId: String, responseRequest: @escaping(detailHandler)) {
        Alamofire.request("\(self.url)\(extractId)").responseJSON(completionHandler: { response in
            switch response.result {
            case .success(_):
                do {
                    let detailResponse = try JSONDecoder().decode(DetailResponse.self, from: response.data!)
                    responseRequest(detailResponse)
                } catch (let error) {
                    print(error)
                }
                
            case .failure(let error):
                print(error)
            }
        })
    }
}
