//
//  DetailModels.swift
//  TesteSantander
//
//  Created by Rodrigo Martins on 29/04/19.
//  Copyright (c) 2019 Rodrigo Martins. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct DetailResponse: Codable {
    var statementList: [DetailData]
    var error: Error?
    
    struct DetailData: Codable {
        var title: String?
        var desc: String?
        var date: String?
        var value: Double?
    }
    
    struct Error: Codable {
        var message: String?
    }
}
