//
//  DetailPresenter.swift
//  TesteSantander
//
//  Created by Rodrigo Martins on 29/04/19.
//  Copyright (c) 2019 Rodrigo Martins. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic{
    func presentUserAccountData(userAccountData: LoginResponse.AccountData) -> Void
    func presentExtractList(data: [DetailResponse.DetailData]?) -> Void
}

class DetailPresenter: DetailPresentationLogic{
    weak var viewController: DetailDisplayLogic?
    
    func presentExtractList(data: [DetailResponse.DetailData]?) {
        if let dataExtratc = data {
            self.viewController?.success(data: dataExtratc)
        }
    }
    
    func presentUserAccountData(userAccountData: LoginResponse.AccountData) {
        if let viewController = self.viewController {
            viewController.renderUserAccountData(userData: userAccountData)
        }
    }
}
